const positions = [
  { id: 0, name: '서버/백엔드' },
  { id: 1, name: '프론트엔드' },
  { id: 2, name: '웹 풀스택' },
  { id: 3, name: '안드로이드 앱' },
  { id: 4, name: '아이폰 앱' },
  { id: 5, name: '크로스플랫폼' },
  { id: 6, name: '머신러닝' },
  { id: 7, name: '인공지능(AI)' },
  { id: 8, name: '데이터 엔지니어' },
  { id: 9, name: 'DBA' },
  { id: 10, name: '모바일 게임' },
  { id: 11, name: '게임 클라이언트' },
  { id: 12, name: '게임 서버' },
  { id: 13, name: '시스템/네트워크' },
  { id: 14, name: '시스템 소프트웨어' },
  { id: 15, name: '데브옵스' },
  { id: 16, name: '인터넷 보안' },
  { id: 17, name: '임베디드 소프트웨어' },
  { id: 18, name: '로보틱스 미들웨어' },
  { id: 19, name: 'QA' },
  { id: 20, name: '사물인터넷(IoT)' },
  { id: 21, name: '응용 프로그램' },
  { id: 22, name: '블록체인' },
  { id: 23, name: '프로젝트 매니저' },
];

export default positions;
