spring:
  datasource:

#    url: jdbc:mysql://localhost:3306/test?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul
#    username: root
#    password: vkqzhs7355!
    url: ${DB_URL}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        # show_sql: true
        format_sql: true
  messages:
    basename: i18n/exception
    encoding: UTF-8
  jwt:
    secret: govlepel@$&
logging.level:
  org.hibernate.SQL: debug
  org.hibernate.type: trace
  
cloud:
  aws:
    s3:
      bucket: teaming17
    region:
      static: ap-northeast-2
    stack:
      auto: false
    credentials:
      instanceProfile: true